### ISSUE TITLE
Bugs and issues

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#1]
Hi

@jails I was studying your code, and some of your postings. A lot of things appear very strange to me.
But first I wonder if you have any further plans to continue develop this VD? When is the next update scheduled?

So, the strange things. When did a 'id' attribute become a property attribute? In your example and in your test cases you write ** props: {  'id': .... }**, This is an attribute, not an property.

In your test cases for CSS styles, you testing for **className**. This is also an attribute, and not a CSS style.

There are also a strange thing going on in the namespaces. See this test cases **patches.spec** - **"patches if different namespaces"** I see that you get no errors on this in the test case which is very strange. If you try your code in a live example, you will get an error. It will then return xmls namespace and not *"testing"*.

And a lot of your code is bloat. Class manipulations, attribute manipulation etc.

Then the performance. Is there any **real** reasons why you jammer on with prototypes everywhere? I you skip many of this prototypes, and try closure or plain javascript. The performance will boost. See citoJs.
It's also very hard for end-devs to remember to create a *new Text*, *new Tag* everytime.

And your children is very hard to understand too. Have you looked at citoJs regarding this?

Two other things is your use of Object(null) instead of {} to create new objects will kill performance too. Long time since I saw that kind of code.

And there are a lot of bugs in your code. After quick testing I got **.render()** is not a function, *parent node not found*, *this.element out of scope* and a couple of 100 more errors.

When this is mentioned, what is your future plans?

**Comment by justmeandtaken** [comment]
@jails Here are couple of other bugs. Take a look at this code lines: https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L338-L341

This will throw because there are no *context*. And the fact that you passing in a boolean argument here, should give trouble because I don't belive a boolean have a element attached to it. 

And with the same, why parentNode? ownerDocument considered it?

**Comment by jails** [comment]
Hi,

yup I'll continue to maintain this virtual dom layer, but I haven't planned any scheduling, I'll just fix bugs as soon I will find them.

Concerning `'id'`, it is both an attribute & an property. Same for class. You can define the class of a DOM element using `element.className=..` as a property, or with `element.setAttribute("class",...` as an attribute.

If you are talking about the `className` in this spec https://github.com/crysalead-js/dom-layer/blob/master/spec/node/setter/apply-attrs-spec.js#L142-176. Indeed, it has nothing to do with the DOM element class name. It's just an abitrary name but yeah using `className` is probably a bit confusing here.

Regarding to https://github.com/crysalead-js/dom-layer/blob/master/spec/node/patch-spec.js#L132-150, indeed this spec is now invalid. The namespace needs to be explicitly passed like in https://github.com/crysalead-js/dom-layer/blob/master/spec/node/setter/apply-attrs-n-s-spec.js#L10-23. And the test passed because it was simply skipped under jsdom and so I forgot to update it.

Sorry I'm not a native english speaker, I don't understand what you meant by "a lot of your code is bloat" but I guess it mean it can be simplified. So just pinpoint some part of the code where some simplification could be done.

The main reason to not use a "plain object" to represent a VD is mainly a matter of choice. To me a VD is not only a bunch of data but should also contain the logic attached to it. Such abstraction can be leveraged to introduce some custom node (in addition to `Tag` & `Text`) which can take control of the sub-tree rendering & patching process. Otherwise you will be limited to the only features implemented by the author for the VD library.

But `Tag` & `Text` are just part of the low VD abstraction, you shouldn't use it in your code. You should rely on your own hyperscript function (like virtual dom did here https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript) which will rely on `Tag` & `Text`.

I'm not sure to get what you meant by "your children is very hard to understand too". Children are an array of virtual node like all other VD around.

I know `{}` is faster but `Object(null)` & `{}` has a different meaning, so you can't them indifferently. Afaik `Object(null)` is only used when it's necessary.

There's probably a couple of bugs around but I leaved a "Warning: work in progress" in the repository, so yeah it's not ready to be used in production. However the [speedtest](http://rawgit.com/crysalead-js/dom-layer/master/examples/speedtest/speedtest.html) example seems to work fine as well as the [vdom-benchmark](http://vdom-benchmark.github.io/vdom-benchmark/), so I'm not sure to get the ".render() is not a function" error as well as the "100 more errors". Feel free to create some issue with some code so I can take a look at.

**Comment by jails** [comment]
Good catch, fixed in https://github.com/crysalead-js/dom-layer/commit/2f92aa90b2d4fb86a45bab32faf8a3ba319fb24d

**Comment by jails** [comment]
And I'm closing this to keep one topic per issue so other people who stumble in it won't be confused.
