### ISSUE TITLE
comment -and script tags

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#14]
@jails Any idea how to create comment and script tags? I can create script-tag, but can't set attributes etc. 

I see that you can do this in CitoJS: https://github.com/joelrich/citojs/blob/master/dist/cito.js#L210-L212

**Comment by jails** [comment]
Is there any use case for this ?

**Comment by justmeandtaken** [comment]
@jails For script tags it would let you append javascript code directly. For comment tags I have seen it been used in templates engines and server side rendering.

You can read this thread:
https://github.com/facebook/react/issues/1035

They avoid to include it in REACT because they want to keep the source light as possible. If over 700KB is light, I don't know.

And for further info, you could look at the ReactiveJS souce. They are also supporting docType and fragments.

And also think about iframe and object tags.

Btw? You are going to support fragments too? CitoJS does this, and ReactiveJS.

**Comment by justmeandtaken** [comment]
@jails You could also look at Facebook bigPipe solution and see how they deal with script tags for each part of their UI. Not sure if this can be adopted to a VD node.

**Comment by jails** [comment]
Making comments or doctypes "dynamic" doesn't makes sense imo. I didn't ever encounter a use case where it would be usefull in a web application and having such feature for some server rendering doesn't make sense either.
If fragments mean "static html", I think it may save some CPU cycles in some use cases but it's more an optimisation than a necessary feature. Anyhow for people who want to make such optimisations they can create a `Fragment` (like the `Tag` function) which just create a `<div>` and sets its content using `innerHTML` on `render()` and forwarding on `patch()` the created `<div>` to the new virtual node.
Personnaly I probably won't ever do that, but imo the API is flexible enough to allow people to deal with what they want by introducing nodes like `Comment`, `Fragment` or `Whatever` if `Tag` & `Text` are not enough for them.

**Comment by justmeandtaken** [comment]
@jails  I understand. But take a look at this section here: https://github.com/joelrich/citojs#fragments

**Comment by jails** [comment]
It can have some use cases since once I needed a `{ children : [ [ ... ] ] }` structure (i.e with one level of nest). But it can be easily be managed by an extra layer like the "hyperscript" function.
For the "make you program simpler" argument, I don't really agree. Imo coding using a virtual dom syntax directly is a bit "overkilling" and it's not the "fragment feature" which will help a lot to make the code a lot cleaner. Moreover if you are using templates like JSX or vanilla html template, this kind of feature will be useless since you will break the bijection between the html template & the virtual dom syntax.
And to conclude about the perfomance, it offers no performance gain. Indeed when the virtual dom parses two vritual trees to check differences you have **no way** to know what has been changed in objects. So comparing two variables using `===` doesn't mean it still contains the same content as the last time you parsed it. So as I understand in its example you will still need to parse `list1` and `list2`.

**Comment by justmeandtaken** [comment]
I'm agree with you too at some point. And my ideal idea for javascript code is too keep it simple, clean and extendable without bloat ( e.g. lot of fancy features).
The "freedom to choose".  And that is more or less what dom-layer has comparing to others.

But what I was thinking about when it comes to Tags, Text and other VD nodes the end-devs can create themself to make things easy without hacking into the code and re-compile, is what about creating a hook for available VD nodes ala a register system? This register keep track over which VD nodes can be used, aka Text and Tag.  In that case the end-devs can have a separate plugin-js file and just to *domLayer.registerNode()* and the code adopts it and ready to use? And this again can be extandable to take advatage of some internal API functions? Or re-use parts from other registred tags through hooks.

**Comment by jails** [comment]
Not sure to get why `domLayer.registerNode()` is needed. end-devs only need to include their plugin file and use their nodes directly ?
```js
var vtree = new Tag('div', {}, [ new Text("hello"), new Comment("my coment"), new Fragment("..") ]);
```
The only requirement is new nodes needs to have a `render()` a `patch()` & a `create()` method.

**Comment by justmeandtaken** [comment]
@jails  Take a look at this lines: https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L947-L951

When I'm testing your example above and got it to work, I encountered issues again.

In the iteration loop I linked too, sometimes it can be plain text or an object, and you get this in your console:  **TypeError: node.render is not a function**

I also noticed that for the text node, node stands as undefined.

**Comment by jails** [comment]
The children array requires some vitural node instance only you probably have a error of syntax, make a fiddle.

**Comment by justmeandtaken** [comment]
Not much to see there. I attached my Comment , and it seems to render. But no comments visible.

https://jsfiddle.net/La4an8j2/4/

**Comment by jails** [comment]
Well seems to work:
![screenshot - 17052015 - 05 12 52](https://cloud.githubusercontent.com/assets/1306941/7668871/77aa5d5e-fc53-11e4-8128-7c418e5f11a2.png)

Btw you should use `element` instead of `node` because dom-layer assume `element` is correctly populated with the DOM element reference so it can be used to be removed/moved/updated etc..

**Comment by justmeandtaken** [comment]
I see it now. Firebug in FF don't show comments, only Chrome dev tools it seems.

**Comment by jails** [comment]
To conclude other virtual nodes than `Tag` & `Text` will be up to end-devs.
