### ISSUE TITLE
unused code

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#17]
Maybe it's only me that don't know what I'm doing, but after a deep analyze of your code, I come up with this:

1. This lines are never used, or what? https://github.com/crysalead-js/dom-layer/blob/master/tree/update.js#L6-L8

2. It seems to never use this code either, and it's almost duplicate of the line above it: https://github.com/crysalead-js/dom-layer/blob/master/node/tag.js#L129-L131

3. This seems never to be reached and used: https://github.com/crysalead-js/dom-layer/blob/master/tree/tree.js#L26-L29
But for this I understand what you thinking, if an array with DOM nodes are returned, and you want to mount multiple?

@jails As it is now, there is no more I can do to help you out now until you publish the event system you wrote you was developing. Then I will be here again and try to help out! Your code seems stable now.

When do you plan to launch the events?

**Comment by jails** [comment]
1. this part allows to pass a function instead of an array. It's like a factory function. So each time a mount point is updated, the factory function is runned again and generates a new vritual tree (or an array of them) for the diffing. So generaly the factory function will return the result of the `render()` function of your "high level" component.

2. this part is executed if you provide your own `destroy` callback. It can be interesting for managing a animation just before removing the dom element. So your `destroy` callback will be called with the callback which actually remove the dom element as parameter that you will run once your "destroy animation" it done. 

3. this part occurs when you are using a selector like a `"class"` which is present several time in the dom. for exemple `mount(".dropdown", function() { /* the dropdown factory */ } )`, but it'll probably be removed or refactored anytime soon.

You can play with classic events but with delegated events I think you will need to wait a week or two.
