### ISSUE TITLE
attributes and properties

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#2]
@jails In the **/setter/apply-attrs** you are setting the attributes directly. But you have another function for this as well in the **domElements**. Shouldn't you have used that function here? As it is now, it's not reacting on null and undefined attributes etc. And there are no option for removing an attribute, is it?

And you are using toLowerCase() for attribute setter, but regarding the upcoming DOM Living specs you shouldn't do that. See this section: **4.8. Interface Element - to set an attribute**

For properties I see the same thing.  You do this for both value and style elements, using functions from **domElement**

For attributes such as class, there will be an issue with SVG elements if you try to set an clasName on a SVG - it will throw something like *"trying to set a property with only a setter"* 

So regarding the classes, you also here should have used functions from domElement, or?
For the class methods are not used anywhere...

Then again, you will get an issue with IE9 that in fact don't have classList support.

**Comment by jails** [comment]
the dom-element library contain 2 convenience methods to get/set and remove attributes using a "dashed-attribute-name" reference as well as the "camelCaseAttributeName" reference. Since the `attrs` object should contain only valid camel case attribute names here, using the DOM element API directly is enough.

`/setter/apply-attrs` is doing a kind of "diff" beetween some previous attribute states and some new ones. So if an attribute is no more present (or === to undefined) it is simply removed https://github.com/crysalead-js/dom-layer/blob/master/node/setter/apply-attrs.js#L14

Not sure to get what you meant by "you are using toLowerCase() for attribute setter", please point out some code with your questions so I can easily figure out your reasoning.

For SVG elements, the className property is not a string but a SVGAnimatedString (in FF ans Chrome) so :
```js
elementSVG.setAttribute('class', value);
```
is the only way to set the class name of a SVG element on FF & Chrome. This library is a just a virtual dom layer which performs the diffing between two valid DOM representations but can't deal with all browser inconsistencies. And afaik for IE based browser you will need to use:
```js
elementSVG.setAttribute('className', value);
```
instead, so imo the best place to deal with this is probably inside an "hyperscript" function which will "adapt" the DOM representation to be valid according to the browser capabilites.

Having a dependency on a library doesn't mean you should use all the methods it provides ;-). And since dom-layer doesn't use classList (through dom-element functions) I didn't provide the polyfill inside https://github.com/crysalead-js/dom-layer/blob/master/polyfill.js so it should work on IE9

**Comment by justmeandtaken** [comment]
@jails Are you planing to add a "hyperscript" function for this?

Regarding the DOM Living specs, this should be in with lowerCase() https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L60

For SVG elements this function will throw for some properties:
https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L82-L100

I looked at the Virtual DOM as you pointed to earlier, and there is a different solution for this, and so have REACT.

**Comment by jails** [comment]
Afaik, attributes must be in camelCase (not  lower case). And since `Tag` is a representation of a DOM element, the `attrs` object will attend attributes with the same naming as DOM element expects for `getAttribute/setAttribute/removeAttribute`. So if people get some hyphened attributes extracted form some html templates, they will need to camel case them first to make it works.

I personnaly don't want to do things like this for properties: https://github.com/facebook/react/blob/1549bae2abb157930e2905a0003ebe4c9fdc1e56/src/browser/ui/dom/SVGDOMPropertyConfig.js (where they explicitly identify what should be an attribute & what should be a property) imo it's up to the developper to know what properties/attributes can be used for a DOM element. If you create an element with `document.createElement/document.createElementNS` and sets as property what should be in an attribute (and vice versa) it won't work . So imo the VD layer is not intended to take care of that. Especially as the behavior is pretty much simple. Only attributes should be used and especially with SVG elements (the class name issue is just because of IE which named is `"className"` instead of `"class"`). Afaik the only few things which must rely on properties are related to input (like selected, checked, etc.), events (like `onclick`, `onchange`) and a couple of other properties I didn't ever used. So it's pretty easy to remember what to fill.

For the "hyperscript" function it's difficult since it can be used in many ways and each time I dealed with a VD implementation, the provided "hyperscript" function was useless. This is for example the one I used for specs https://github.com/crysalead-js/dom-layer/blob/master/spec/helper/h.js#L4-20, but you can imagine handling high level component which must be attached to specific dom node. And the "hyperscript" function will create as the same time an instance of a component and attach it with a created `Tag` element.

So it's difficult to provide something flexible enough since it'll generaly depends on a higher choosed achitecture so I'll probably take care about the `class` thingy issue for attributes for IE so it'll be renamed to "className" if IE is detected to make it works out of the box.

**Comment by justmeandtaken** [comment]
@jails Yup, it make sense. One last question in this issue is, how is your idea on adding event handling and xhr? For events I see you have an empty *{}*.

**Comment by jails** [comment]
You can add event handling using `props`. like `props: { onclick: function(){/* ... */} }` and the onclick function will be executed when the click event will be triggered on the DOM element.

And `events` is actually unused since I'm working on it right now. The main idea is that the stored events in this object will be managed differently. With classic events, you run sometime into complex event resolutions. Like you have a menu, you wan't it to be closed when the user click outside of the menu area, but for example if the user click on another widget which use `stopPropagation` the menu still open since the `document.body` (where the close logic is attached) won't receive the click event. (further reading at https://css-tricks.com/dangers-stopping-event-propagation/)

So I planned to solve this a bit differently by attaching all events present in `events` onto `document.body` and the event will be forwarded to the target element instead. Afaik is how ReactJS deals with events (https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#under-the-hood-autobinding-and-event-delegation). So right now I'm writing a library for "event delegation" so `events` will work out of the box.

**Comment by justmeandtaken** [comment]
@jails   You can close this issue, but a few last questions. 

1. Life cycle events as in REACT. Going to be supported?
2. Is there a granular control over a diff, e.g. React's shouldComponentUpdate?
3. Is there any options to update a node? Say you have an checkbox and checked set to true, how you do it if you want to update the node so that the checkbox become false?
4. Any ideas about XHR support?

**Comment by jails** [comment]
1. Life cycle events belongs to the React framework, not the React VD Layer. The only events are `'created'` when a tag node has been created & `'remove'` when a tag node is going to be removed (well it's attached DOM element). See https://github.com/crysalead-js/dom-layer/blob/master/node/tag.js#L74 and https://github.com/crysalead-js/dom-layer/blob/master/node/tag.js#L137. But you can use your own `Tag` implementation with the callback you want in.

2. Same here `shouldComponentUpdate` is a strategy which belongs to a framework level. There's a lot of possible strategies here, for example you can use your own `Tag` implementation which control the patching (see https://github.com/crysalead-js/dom-layer/blob/master/node/tag.js#L86) so accroding to some "conditions" the patching is bailed out or not (anyhow it's not the way it should be done, imo this kind of refresh strategy must belongs to a kind of `Component` which is composed by some `Tag` & `Text` node through a `render()` function, and it will be responsible of the updates).

3. You need to implement a [rendering loop](https://github.com/crysalead-js/dom-layer#the-rendering-loop). But the dom-layer is defintly not a framework. You should build your own on top of it. Right now my framework layer is not ready so I can't show you but if you are interested of what it should look like just take a look at (deku)[https://github.com/segmentio/deku]. It's close to what I'm trying the achieve.

4. XHR ? you mean XMLHttpRequest ? Just use vanilla JS or this https://www.npmjs.com/package/xhr which will also work in node.
