### ISSUE TITLE
select multiple

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#20]
You are setting select multiple as a property. Not as an attributes. This means that you never can get multiple as an attribute as the specs says you should.

if you set it as an property, the attribute **multiple** would be **multiple=""**. So then if you try to grab it as an attribute, you get nothing, but should have got multiple.

A select multiple can also have other values - e,g,  x, foo, bar.  This will not work either.

With the property you are only setting multiple like this: 

```javascript
 <select multiple>
```
So this can't be done:

```javascript

- <select multiple="multiple">
- <select multiple="false">  // should return undefined
- <select multiple="x">
```
As stated here, it's an attribute too. But it doesnt work like that.

https://html.spec.whatwg.org/#the-select-element

In pure vanila javascript, you can do this:

```javascript

<select></select> // html

// console.log:  <select multiple="multiple"></select>
document.getElementsByTagName("select")[0].setAttribute("multiple", "multiple");
```

There are also other similar issues for other attributes. I just mention this because it can cause conflicts with other libraries such as jQuery or in this case vanila javascript. 

**UPDATE** I was testing on a old version, half working on new once, but still a few issues to figure out here.

**Comment by jails** [comment]
Yup and I see no possible workaround. All stuff related to input must be set as a `props` (except value which must be in `attrs`) and everything else must be in `attrs`. React has the same requirement (https://github.com/facebook/react/blob/52752446760dee0bc7232b4146f5a309ac57f065/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L119). And the reason in the following. if you have the following `attrs: { multiple: "multiple", value ["a", "b"] }` on a select, you have no way to know which attribute is going to be applied first. So if `applyAttrs` set `multiple` first and then `value` it will work, otherwise it won't work if `applyAttrs` set `value` first.

**Comment by justmeandtaken** [comment]
If you are going to use React's requirement a lot need to be changed in the code. See SVG where a lot of the attributes has to be set as a property, select as an property ( *today set as attribute*) etc. etc
