### ISSUE TITLE
should remove callbacks in _events

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#24]
all event callbacks that are stored in the **this._events** should be removed from here if the event no longer in use / the event get unbinded or node removed or tree unmounted.

**Comment by jails** [comment]
I guess this issue is related to the `dom-event-manager` plugin. However I don't understand what you mean. You are no way to know in advance what kind of events are in use or not. However if you are sure you are using only a couple of events, you can bind them explicitly instead of calling `init()`

```js
var domLayer = require("dom-layer");
var eventManager = domLayer.events.getManager();
eventManager.bind("click");
eventManager.bind("input");

// only the `onclick` & the `oninput` callback will work in `events`.

```

**Comment by justmeandtaken** [comment]
I was just thinking of this: https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L22
I guess all event callbacks you are using are attached here?
So if you have one child node with event and callback, should this callback still exist in this array if the node and event are no longer?

**Comment by jails** [comment]
`events` are attached to the virtual tree, so when you patch a tree to another the new one is used instead of the old one, so you don't need to take care about what the old virtual tree hold, it's not used anymore and can be discarded once the patching is done. However the `domLayerNode` property of the DOM element needs to updated accroding its new node reference if it's that you were talking about https://github.com/crysalead-js/dom-layer/commit/a24a38ac36220bfc010e619c69241457b22ef87e
