### ISSUE TITLE
improve toHTML()

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#28]
Hi, take a look at this code taken from ReactiveJS. Any ideas here to improve your methods_

```javascript

 var Element_prototype_toString = function () {
  	var str, escape;

  	if (this.template.y) {
  		// DOCTYPE declaration
  		return "<!DOCTYPE" + this.template.dd + ">";
  	}

  	str = "<" + this.template.e;

  	str += this.attributes.map(stringifyAttribute).join("") + this.conditionalAttributes.map(stringifyAttribute).join("");

  	// Special case - selected options
  	if (this.name === "option" && optionIsSelected(this)) {
  		str += " selected";
  	}

  	// Special case - two-way radio name bindings
  	if (this.name === "input" && inputIsCheckedRadio(this)) {
  		str += " checked";
  	}

  	str += ">";

  	// Special case - textarea
  	if (this.name === "textarea" && this.getAttribute("value") !== undefined) {
  		str += escapeHtml(this.getAttribute("value"));
  	}

  	// Special case - contenteditable
  	else if (this.getAttribute("contenteditable") !== undefined) {
  		str += this.getAttribute("value") || "";
  	}

  	if (this.fragment) {
  		escape = this.name !== "script" && this.name !== "style";
  		str += this.fragment.toString(escape);
  	}

  	// add a closing tag if this isn't a void element
  	if (!voidElementNames.test(this.template.e)) {
  		str += "</" + this.template.e + ">";
  	}

  	return str;
  };```

**Comment by jails** [comment]
I fixed the rendering of the style attribute here https://github.com/crysalead-js/dom-layer/commit/eb0783ca89237e6f61030b6c5cc9b3c22f03a086
However I don't get the special cases. `<textarea>` doesn't have any value attribute only a value property. So `<textarea value="Hello World!"></textarea>` is invalid. It must be `<textarea>Hello World!</textarea>`. Same for `contenteditable`.
Since in dom-layer setting the value attribute also set the value property the value attribute can be used out of the box. However for server side rendering I'm filtering them out https://github.com/crysalead-js/dom-layer/commit/9df64963f90869f703f8e3ef010c5a9f4fe42f9c . If people wants a default value for a textarea they will need to correctly set up the children array with a textual node.
If I'm rendering a value attribute as a textual node during `toHtml()`, the generated html won't match the virtual tree any more and it won't be possible to use `attach()` on the rendered html.
