### ISSUE TITLE
audio/video

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#34]
I open this ticket so you can check this out: https://github.com/facebook/react/issues/3010

**Comment by jails** [comment]
It shouldn't be an issue if your `<audio>`/`<video>` tag has a key defined (so it'll be moved instead of recreated on updates). And you set the default `mute` value has an attribute like the following:
```html
<video controls="controls" mute="mute">
```
so the mute state would stay perserved if you don't play with muted in `props`. Otherwise you will need to create you own `Audio` or `Video` virtual node if you need a full control on this uncontrollable property by customizing the `patch()` method.
