### ISSUE TITLE
method for updating children?

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#41]
I saw Kivi, and CitoJS have API methods for updating children only. How is this to be done from dom-layer?

**Comment by jails** [comment]
API ? what kind of API ?

**Comment by rickardjanson** [comment]
If you can call it an API, anyway this is what CitoJS expose to the global namespace: https://github.com/joelrich/citojs/blob/master/dist/cito.js#L1238-L1269

So:  `citojs.vdom.updateChildren` can be reached from everywhere.

I just took this as an example, because CitoJS took most of it's code from Kivi/Mithril.

**Comment by jails** [comment]
This is where it is exposed, however you should'nt need to call it directly. In dom-layer you can deal with either a single node or an array of virtual nodes both work witch is not the case for many implementation which requires a single virtual node as root element. The following is for example possible:

```js
var mountId = tree.mount("#mount-point", [ new Tag("div"), new Tag("span") ]);
tree.update(mountId, [ new Tag("span"), new Tag("div") ]);
``` 
Anyhow the `update` method is exposed here https://github.com/crysalead-js/dom-layer/blob/master/index.js#L20 however you shouldn't need it. Since all updates can be don though a tree.

**Comment by rickardjanson** [comment]
Got it !!  Btw. What is the roadmap for dom-layer now? And what changes will come next? A component layer?

**Comment by jails** [comment]
I think I'm almost done with this library. So yeah the next step is to build a component library on top of it. So I'll probably need to adjust some missing stuff I'm not aware of right now but will when I'll need them for the component library.
However I'll probably add some more specs around to chase some potential bugs.
