### ISSUE TITLE
value types?

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#65]
Hi. Should you consider to use value types? I asked the same question in another repo where I'm helping with bug testing. Seems that would be the new big thing, and REACT are supporting it from 0.14.
Ref: https://github.com/facebook/react/issues/3226

**Comment by jails** [comment]
It's not really a feature, it's a transpiling optimisation. So it's only relevant with a templating language like JSX or similar. It would be interesting to see the performance gain because it looks like a more a micro optimisation btw. Not sure React will be able to came back into the game with such micro optimisation.
