### ISSUE TITLE
mount on document throws

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#7]
@jails If you try to mount on **document** it throws, but works if you mount on **document.body**. However it will throw again if you don't have a **document.body**.

Mounting on **document.documentElement** works.

**Comment by jails** [comment]
Yup, it throws an error with `document` because it's not supposed to with `document` since it's not a DOM element. And `document.documentElement` returns the dom element that is the root element of the `document` (so most of the time the `<html>` element). But I wouldn't use `<html>` as a mounting point personally.
